import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/app/globals.css';
import TopBar from '@/components/TopBar';
import { Locale } from '@/dictionaries';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

const nunitoSans = localFont({ src: '../../public/fonts/NunitoSans.ttf', weight: '400' });

export const metadata: Metadata = {
  title: 'CLEAR',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}) => {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${nunitoSans.className} flex h-screen flex-col antialiased`}>
        <NextIntlClientProvider>
          <TopBar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
